export const PORTRAIT_BASE = "/assets/game/portraits";
export const CHIBI_BASE = "/assets/game/characters/chibi";
export const ENVIRONMENT_BASE = "/assets/game/environments";

export const ROLL_CARDS = [
  {
    seed: "QM-008-7134",
    aptitude: "丙等上",
    aperture: "四成七",
    fate: "天外之魔",
    talents: ["酒虫亲和", "善藏气息"],
    flaw: "命薄福浅",
    background: "古月旁支 · 旧屋负债",
    attributes: [
      { id: "root", label: "根骨", value: 48, tone: "neutral" },
      { id: "insight", label: "悟性", value: 76, tone: "good" },
      { id: "soul", label: "神魂", value: 58, tone: "neutral" },
      { id: "agility", label: "身法", value: 72, tone: "good" },
      { id: "charm", label: "魅力", value: 44, tone: "warning" },
      { id: "mind", label: "心性", value: 63, tone: "neutral" },
      { id: "luck", label: "气运", value: 39, tone: "danger" },
      { id: "memory", label: "原著记忆", value: 88, tone: "special" },
      { id: "theft", label: "盗道天赋", value: 81, tone: "special" },
    ],
  },
  {
    seed: "QM-009-1182",
    aptitude: "乙等下",
    aperture: "六成一",
    fate: "盗门余孽",
    talents: ["袖里乾坤", "商道敏感"],
    flaw: "身份破绽",
    background: "古月旁支 · 商队旧识",
    attributes: [
      { id: "root", label: "根骨", value: 61, tone: "neutral" },
      { id: "insight", label: "悟性", value: 59, tone: "neutral" },
      { id: "soul", label: "神魂", value: 52, tone: "neutral" },
      { id: "agility", label: "身法", value: 83, tone: "good" },
      { id: "charm", label: "魅力", value: 68, tone: "good" },
      { id: "mind", label: "心性", value: 47, tone: "warning" },
      { id: "luck", label: "气运", value: 55, tone: "neutral" },
      { id: "memory", label: "原著记忆", value: 70, tone: "special" },
      { id: "theft", label: "盗道天赋", value: 92, tone: "special" },
    ],
  },
  {
    seed: "QM-010-5609",
    aptitude: "丁等",
    aperture: "三成二",
    fate: "空窍残缺",
    talents: ["早慧少年", "盗心澄明"],
    flaw: "天意注视",
    background: "古月旁支 · 无人问津",
    attributes: [
      { id: "root", label: "根骨", value: 36, tone: "danger" },
      { id: "insight", label: "悟性", value: 91, tone: "good" },
      { id: "soul", label: "神魂", value: 74, tone: "good" },
      { id: "agility", label: "身法", value: 65, tone: "neutral" },
      { id: "charm", label: "魅力", value: 41, tone: "warning" },
      { id: "mind", label: "心性", value: 82, tone: "good" },
      { id: "luck", label: "气运", value: 28, tone: "danger" },
      { id: "memory", label: "原著记忆", value: 96, tone: "special" },
      { id: "theft", label: "盗道天赋", value: 78, tone: "special" },
    ],
  },
];

export const GU_WORMS = [
  {
    id: "moonlight",
    name: "月光蛊",
    rank: "一转",
    path: "月道",
    state: "active",
    stateLabel: "活跃",
    essence: 5,
    feed: "月兰花瓣",
    feeding: 74,
    nextFeed: "3 日",
    effect: "凝成月刃，造成中距伤害。",
    owner: "古月砚",
    mark: "月",
  },
  {
    id: "wine-worm",
    name: "酒虫",
    rank: "一转",
    path: "食道",
    state: "wild",
    stateLabel: "野生",
    essence: 0,
    feed: "青竹酒",
    feeding: 42,
    nextFeed: "今夜",
    effect: "精炼一转真元，提升修炼效率。",
    owner: "无主 · 正在争夺",
    mark: "酒",
  },
  {
    id: "hidden-breath",
    name: "匿息蛊",
    rank: "一转",
    path: "盗道",
    state: "hungry",
    stateLabel: "缺食",
    essence: 3,
    feed: "暮蝉蜕",
    feeding: 18,
    nextFeed: "1 日内",
    effect: "收束气息，潜行判定 +5。",
    owner: "古月砚",
    mark: "匿",
  },
  {
    id: "jade-skin",
    name: "玉皮蛊",
    rank: "一转",
    path: "防御",
    state: "dormant",
    stateLabel: "未炼化",
    essence: 4,
    feed: "青玉粉",
    feeding: 0,
    nextFeed: "炼化后",
    effect: "皮肤如玉，降低刀兵伤害。",
    owner: "学堂蛊室",
    mark: "玉",
  },
];

export const INVENTORY_ITEMS = [
  {
    id: "primeval-stone",
    name: "元石",
    type: "resource",
    typeLabel: "资源",
    count: 18,
    owner: "古月砚",
    state: "normal",
    mark: "石",
  },
  {
    id: "bamboo-wine",
    name: "青竹酒",
    type: "quest",
    typeLabel: "任务",
    count: 2,
    owner: "古月砚",
    state: "quest",
    mark: "酒",
  },
  {
    id: "old-key",
    name: "旧屋铜钥",
    type: "key",
    typeLabel: "钥物",
    count: 1,
    owner: "古月砚",
    state: "bound",
    mark: "钥",
  },
  {
    id: "academy-token",
    name: "蛊室令牌",
    type: "stolen",
    typeLabel: "赃物",
    count: 1,
    owner: "学堂值守",
    heldBy: "古月砚",
    state: "stolen",
    mark: "令",
  },
  {
    id: "debt-note",
    name: "旁支债据",
    type: "evidence",
    typeLabel: "证据",
    count: 1,
    owner: "禾娘",
    heldBy: "古月砚",
    state: "hidden",
    mark: "据",
  },
  {
    id: "moon-orchid",
    name: "月兰花瓣",
    type: "material",
    typeLabel: "蛊材",
    count: 6,
    owner: "古月砚",
    state: "normal",
    mark: "兰",
  },
  {
    id: "healing-paste",
    name: "止血膏",
    type: "consumable",
    typeLabel: "消耗",
    count: 1,
    owner: "古月砚",
    state: "normal",
    mark: "药",
  },
  {
    id: "empty-slot",
    name: "空位",
    type: "empty",
    typeLabel: "空",
    count: 0,
    owner: "",
    state: "empty",
    mark: "+",
  },
];

export const MAP_LOCATIONS = [
  {
    id: "old-house",
    name: "旁支旧屋",
    x: 74,
    y: 70,
    ap: 1,
    danger: "安稳",
    state: "open",
    scene: "dorm",
  },
  {
    id: "academy",
    name: "古月学堂",
    x: 73,
    y: 24,
    ap: 1,
    danger: "戒备",
    state: "open",
    scene: "academy",
  },
  {
    id: "tavern",
    name: "山脚酒肆",
    x: 51,
    y: 63,
    ap: 1,
    danger: "人多眼杂",
    state: "open",
    scene: "tavern",
  },
  {
    id: "flower-wine-cave",
    name: "花酒行者洞口",
    x: 30,
    y: 50,
    ap: 1,
    danger: "高风险",
    state: "current",
    scene: "forest-battle",
  },
  {
    id: "gu-storage",
    name: "家族蛊室",
    x: 79,
    y: 38,
    ap: 2,
    danger: "重兵值守",
    state: "locked",
    condition: "学堂功绩 30 或蛊室令牌",
    scene: "academy",
  },
  {
    id: "wolf-valley",
    name: "狼谷",
    x: 18,
    y: 73,
    ap: 2,
    danger: "未侦察",
    state: "locked",
    condition: "第 18 日后开放",
    scene: "forest-battle",
  },
];

export const QUESTS = [
  {
    id: "Q01",
    title: "酒虫归属",
    kind: "主线机缘",
    window: "第 3-8 日",
    status: "searching",
    statusLabel: "争夺中",
    progress: 76,
    next: "用青竹酒完成最后一次诱引",
    repair: "若方源先取得，可转为交易、偷取或追踪传承。",
  },
  {
    id: "Q02",
    title: "商队旧识",
    kind: "缘线",
    window: "第 9-18 日",
    status: "hinted",
    statusLabel: "已提示",
    progress: 24,
    next: "处理旁支债据，保留与禾娘的联系",
    repair: "商队离寨前仍可补救。",
  },
  {
    id: "Q03",
    title: "贾金生之死",
    kind: "调查",
    window: "第 19-26 日",
    status: "locked",
    statusLabel: "未发生",
    progress: 8,
    next: "留意商队账册和酒肆目击者",
    repair: "证据缺失会改变铁家审问难度。",
  },
  {
    id: "Q04",
    title: "青书生路",
    kind: "人物命运",
    window: "第 18-29 日",
    status: "hinted",
    statusLabel: "伏笔",
    progress: 18,
    next: "建立青书信任，寻找狼潮替代战术",
    repair: "错过一次救援仍可在回溯修正中选择。",
  },
  {
    id: "Q05",
    title: "白凝冰的兴趣",
    kind: "危险缘线",
    window: "第 21-30 日",
    status: "locked",
    statusLabel: "未接触",
    progress: 0,
    next: "让自身进入白家侦察范围",
    repair: "不可同时维持完全隐匿路线。",
  },
];

export const SOURCE_OPPORTUNITIES = [
  {
    id: "wine-worm",
    title: "酒虫与花酒行者遗藏",
    subject: "方源",
    horizon: "current",
    horizonLabel: "今年",
    type: "gu",
    typeLabel: "蛊虫",
    owner: "方源（原定）",
    window: "第 3-8 日 · 今夜关闭",
    location: "青茅山 · 花酒行者洞口",
    faction: "无主机缘",
    provenance: "verified",
    provenanceLabel: "已验证事实",
    feasibility: 84,
    reachable: true,
    method: "以两坛青竹酒分段诱引；保留退路，避免与方源同时进入窄洞。",
    reward: "酒虫、修炼效率 +30%、花酒传承入口",
    consequence: "方源警觉 +20；原文同步率预计 -8%",
    summary: "方源原定在开窍后取得酒虫，并由此发现花酒行者遗藏。",
    tags: ["方源", "酒虫", "花酒行者", "青竹酒"],
  },
  {
    id: "jia-jin-sheng-ledger",
    title: "贾金生私账与死亡窗口",
    subject: "贾金生",
    horizon: "current",
    horizonLabel: "今年",
    type: "item",
    typeLabel: "物品",
    owner: "贾金生",
    window: "第 18-24 日",
    location: "商队驻地 / 山脚酒肆",
    faction: "贾家商队",
    provenance: "original",
    provenanceLabel: "原作记录",
    feasibility: 61,
    reachable: true,
    method: "先取得私账拓印，再决定救人、栽赃或保留原轨。",
    reward: "商路、账册证据、贾富谈判筹码",
    consequence: "铁家追查提前；商队关系可能断裂",
    summary: "私账会在贾金生死亡后成为多方争夺的证据。",
    tags: ["贾金生", "账册", "铁家", "商队"],
  },
  {
    id: "white-boar-gu",
    title: "白豕蛊收购缺口",
    subject: "古月漠北",
    horizon: "current",
    horizonLabel: "今年",
    type: "gu",
    typeLabel: "蛊虫",
    owner: "家族蛊室",
    window: "第 11-16 日",
    location: "古月山寨 · 蛊室",
    faction: "古月一族",
    provenance: "inference",
    provenanceLabel: "当前推演",
    feasibility: 53,
    reachable: true,
    method: "利用蛊室令牌制造盘点差额，或以功绩公开换取。",
    reward: "一猪之力；力量判定 +15",
    consequence: "蛊室所有权追查；正道声望 -4",
    summary: "族中竞争会制造短暂的库存调拨窗口。",
    tags: ["白豕蛊", "蛊室", "力道", "功绩"],
  },
  {
    id: "shang-xin-ci-caravan",
    title: "商心慈南下商队",
    subject: "商心慈",
    horizon: "one-year",
    horizonLabel: "未来一年",
    type: "character",
    typeLabel: "人物",
    owner: "商心慈（原定命运）",
    window: "离山后第 4-7 月",
    location: "南疆商路",
    faction: "商家",
    provenance: "original",
    provenanceLabel: "原作记录",
    feasibility: 32,
    reachable: false,
    method: "先取得商队身份与南下路线；青茅山篇仅可标记索引。",
    reward: "商家入口、长期商道关系",
    consequence: "偏离青茅山越远，原文时间精度越低",
    summary: "未来商队节点可成为离山后的首个长期关系入口。",
    tags: ["商心慈", "商队", "南疆", "缘线"],
  },
  {
    id: "tie-investigation",
    title: "铁家父女调查青茅山",
    subject: "铁若男",
    horizon: "one-year",
    horizonLabel: "未来一年",
    type: "faction",
    typeLabel: "势力",
    owner: "铁家",
    window: "贾金生案发后",
    location: "青茅山三寨",
    faction: "铁家",
    provenance: "verified",
    provenanceLabel: "已验证事实",
    feasibility: 47,
    reachable: true,
    method: "提前整理不在场证明，并把可验证事实与推演分开保存。",
    reward: "调查合作、洗清嫌疑、铁家证据链",
    consequence: "任何伪证都会成为永久追查标记",
    summary: "铁血冷与铁若男会沿贾金生之死建立证据闭环。",
    tags: ["铁若男", "铁血冷", "贾金生", "证据"],
  },
  {
    id: "bai-ning-bing-awakening",
    title: "白凝冰的十绝体终局",
    subject: "白凝冰",
    horizon: "three-years",
    horizonLabel: "未来三年",
    type: "character",
    typeLabel: "人物",
    owner: "白凝冰",
    window: "狼潮前后",
    location: "白家寨 / 青茅山",
    faction: "白家",
    provenance: "original",
    provenanceLabel: "原作记录",
    feasibility: 28,
    reachable: false,
    method: "以危险对手身份建立可重复接触；不可直接公开十绝体未来。",
    reward: "白凝冰缘线、冰道情报、狼潮变量",
    consequence: "杀意与兴趣同步增长；方源会重新评估玩家",
    summary: "北冥冰魄体带来的自爆压力会支配白凝冰的选择。",
    tags: ["白凝冰", "十绝体", "白家", "狼潮"],
  },
  {
    id: "three-kings-inheritance",
    title: "三王传承开放",
    subject: "三王传承",
    horizon: "three-years",
    horizonLabel: "未来三年",
    type: "inheritance",
    typeLabel: "传承",
    owner: "无主（原定群雄争夺）",
    window: "离山后约三年",
    location: "三叉山",
    faction: "南疆群雄",
    provenance: "original",
    provenanceLabel: "原作记录",
    feasibility: 12,
    reachable: false,
    method: "只保留索引；需先建立跨域交通、三转战力与新身份。",
    reward: "奴道、炼道与犬王传承机会",
    consequence: "当前行动无法建立可靠因果链",
    summary: "远期大型传承，只能作为章节后路线锚点。",
    tags: ["三王传承", "三叉山", "传承", "南疆"],
  },
];

export const RELATIONSHIPS = [
  {
    id: "fang-yuan",
    name: "古月方源",
    role: "同届 · 原作主角",
    trust: 18,
    suspicion: 38,
    leverage: 24,
    contact: "可接触",
    status: "在场",
    metric: "警觉 38",
    portrait: `${CHIBI_BASE}/chibi_fang_yuan.png`,
    lastEvent: "你与他同时追到花酒行者洞口。",
  },
  {
    id: "fang-zheng",
    name: "古月方正",
    role: "同届 · 甲等资质",
    trust: 57,
    suspicion: 12,
    leverage: 31,
    contact: "可交谈",
    status: "在场",
    metric: "自尊压力 44",
    portrait: `${CHIBI_BASE}/chibi_npc_clan_steward.png`,
    lastEvent: "他接受了你的炼化建议。",
  },
  {
    id: "he-niang",
    name: "禾娘",
    role: "旁支旧识 · 债权人",
    trust: 42,
    suspicion: 28,
    leverage: 66,
    contact: "明夜可见",
    status: "在场",
    metric: "债务 12 元石",
    portrait: `${PORTRAIT_BASE}/portrait_npc_caravan_manager_normal.png`,
    lastEvent: "她将旧债据留给你一夜。",
  },
  {
    id: "clan-steward",
    name: "古月兰心",
    role: "家族管事",
    trust: 36,
    suspicion: 41,
    leverage: 19,
    contact: "需预约",
    status: "在场",
    metric: "家族评价 中立",
    portrait: `${PORTRAIT_BASE}/portrait_npc_clan_steward_normal.png`,
    lastEvent: "她注意到蛊室令牌的交接记录。",
  },
  {
    id: "tavern-keeper",
    name: "青竹娘",
    role: "酒肆掌柜",
    trust: 63,
    suspicion: 21,
    leverage: 48,
    contact: "营业时可见",
    status: "在场",
    metric: "酒肆耳目 2",
    portrait: `${PORTRAIT_BASE}/portrait_npc_tavern_keeper_normal.png`,
    lastEvent: "她替你留下两坛气味最重的青竹酒。",
  },
];

export const DIALOGUE_CHOICES = [
  {
    id: "offer",
    label: "把一坛酒推向方源",
    detail: "以交易测试他的底线，同时保留第二坛酒。",
    ap: 1,
    risk: "中",
    check: "魅力 44 + 原著记忆 8 vs 警觉 38",
    available: true,
  },
  {
    id: "race",
    label: "抢先进入窄洞",
    detail: "依靠身法夺取第一接触权。",
    ap: 1,
    risk: "高",
    check: "身法 72 + 准备 5 vs 方源先手 64",
    available: true,
  },
  {
    id: "steal",
    label: "等他出手后偷换酒坛",
    detail: "触发盗道检定；失败会留下可追溯气息。",
    ap: 2,
    risk: "极高",
    check: "盗道 81 + 匿息 5 vs 环境 72",
    available: true,
  },
  {
    id: "memory",
    label: "直接说出花酒行者",
    detail: "暴露超出身份的信息。",
    ap: 0,
    risk: "永久",
    check: "需要：方源警觉低于 20",
    available: false,
  },
];

export const EVIDENCE = [
  {
    id: "wine-smell",
    title: "青竹酒残香",
    category: "物证",
    source: "山脚酒肆",
    status: "confirmed",
    x: 16,
    y: 24,
  },
  {
    id: "tavern-witness",
    title: "掌柜目击",
    category: "人证",
    source: "青竹娘",
    status: "confirmed",
    x: 46,
    y: 14,
  },
  {
    id: "ledger-copy",
    title: "私账拓印",
    category: "账证",
    source: "贾金生货箱",
    status: "hidden",
    x: 73,
    y: 28,
  },
  {
    id: "missing-hour",
    title: "酉时空档",
    category: "时间线",
    source: "商队口供",
    status: "suspicious",
    x: 30,
    y: 60,
  },
  {
    id: "false-footprint",
    title: "后窗脚印",
    category: "痕迹",
    source: "案发现场",
    status: "forged",
    x: 61,
    y: 64,
  },
  {
    id: "player-alibi",
    title: "旧屋灯火",
    category: "不在场证明",
    source: "邻屋口供",
    status: "suspicious",
    x: 17,
    y: 82,
  },
  {
    id: "iron-chain",
    title: "铁家闭环",
    category: "结论",
    source: "尚未建立",
    status: "locked",
    x: 83,
    y: 76,
  },
];

export const DAY_END_ACTIONS = [
  {
    id: "cultivate",
    title: "闭门修炼",
    icon: "sparkles",
    gain: "修炼进度 +12",
    cost: "月兰花瓣 ×1",
    risk: "酒虫若未炼化，收益不变",
  },
  {
    id: "earn",
    title: "替酒肆跑腿",
    icon: "coins",
    gain: "元石 +4，掌柜信任 +3",
    cost: "疲惫 +8",
    risk: "错过夜间人物事件",
  },
  {
    id: "practice",
    title: "练习盗取",
    icon: "hand",
    gain: "盗道熟练 +9",
    cost: "暴露 +4",
    risk: "可能生成失主线索",
  },
  {
    id: "relationship",
    title: "拜访禾娘",
    icon: "messages-square",
    gain: "债务延期，关系 +6",
    cost: "元石 -2",
    risk: "家族管事得知旧债",
  },
  {
    id: "feed",
    title: "照料蛊虫",
    icon: "bug",
    gain: "月光蛊饱食 +25",
    cost: "月兰花瓣 ×2",
    risk: "匿息蛊仍缺食",
  },
];

export const ENDING_ROUTES = [
  {
    id: "clan",
    code: "E01",
    title: "家族撤离令",
    status: "available",
    requirement: "功绩 ≥ 15 · 家族信任 ≥ 30",
    cost: "放弃商队与隐藏身份",
    carry: "月光蛊、家族凭证、2 名同行者",
  },
  {
    id: "merchant",
    code: "E02",
    title: "随商队南下",
    status: "available",
    requirement: "商队关系 ≥ 40 · 清偿半数债务",
    cost: "元石 -8 · 暂时暴露行踪",
    carry: "交易身份、禾娘人物卡、南疆索引",
  },
  {
    id: "fang-yuan",
    code: "E03",
    title: "与方源交易",
    status: "danger",
    requirement: "警觉 < 60 · 持有对等筹码",
    cost: "交出一项原文机缘",
    carry: "高风险同路关系、未来试探事件",
  },
  {
    id: "bai",
    code: "E04",
    title: "白家险路",
    status: "locked",
    requirement: "白凝冰兴趣 ≥ 30",
    cost: "追杀概率极高",
    carry: "冰道线索、危险缘线",
  },
  {
    id: "solo",
    code: "E05",
    title: "独自越岭",
    status: "available",
    requirement: "身法 ≥ 65 · 补给 ≥ 3",
    cost: "随机损失一件非绑定物品",
    carry: "完全自由身份、全部隐秘",
  },
  {
    id: "fallback",
    code: "E06",
    title: "灾后流民",
    status: "fallback",
    requirement: "兜底路线",
    cost: "资源保留上限 3 格",
    carry: "永久伤势、未知落点、主线继续",
  },
];

export const DEMO_STATE = {
  ui: {
    selectedPanel: "UI08",
    rollIndex: 0,
    activeGuId: "wine-worm",
    inventoryFilter: "all",
    activeQuestId: "Q01",
    activeRelationId: "fang-yuan",
    queryHorizon: "current",
    queryType: "all",
    queryText: "",
    activeOpportunityId: "wine-worm",
    activeDialogueChoice: "",
    checkOutcome: "success",
    combatAction: "",
    activeEvidenceId: "wine-smell",
    dayEndAction: "cultivate",
    rollbackChoice: "save-qing-shu",
    endingRoute: "merchant",
    generatorStage: "ready",
  },
  world: {
    chapter: "青茅山篇",
    act: 2,
    actLabel: "第二幕 · 截胡者",
    day: 8,
    time: "酉初",
    location: "花酒行者洞口",
    weather: "山雾渐浓",
    tension: 46,
  },
  player: {
    name: "古月砚",
    title: "旁支少年 · 天外之魔",
    portrait: `${CHIBI_BASE}/chibi_player.png`,
    rank: "一转初阶",
    aperture: "丙等上",
    health: { current: 84, max: 100 },
    essence: { current: 31, max: 47 },
    ap: { current: 2, max: 3 },
    stones: 18,
    fatigue: 27,
    exposure: 38,
    merit: 16,
    debt: 12,
    bloodPollution: 4,
    cultivation: 43,
    theftRank: "梁上手",
    theftMastery: 68,
    attributes: ROLL_CARDS[0].attributes,
    buffs: [
      {
        id: "source-flash",
        name: "原著灵光",
        layer: "临时",
        effect: "下次剧情识别 +10",
        tone: "good",
      },
      {
        id: "hidden-breath",
        name: "匿息",
        layer: "临时",
        effect: "潜行 +5 · 今夜结束",
        tone: "good",
      },
      {
        id: "fang-test",
        name: "方源试探",
        layer: "剧情",
        effect: "可能触发暗查",
        tone: "danger",
      },
      {
        id: "gu-hunger",
        name: "蛊虫饥饿",
        layer: "长期",
        effect: "匿息蛊效果 -50%",
        tone: "warning",
      },
      {
        id: "otherworldly",
        name: "天外之魔",
        layer: "命格",
        effect: "原著记忆 +20 · 天意关注 +10",
        tone: "special",
      },
    ],
  },
  generator: {
    sourceFile: "蛊真人.txt",
    mode: "完整世界",
    identity: "保留现实认知",
    sourceSync: 92,
    queryDepth: "未来三年",
    rules: 100,
    relationships: 100,
    irreversibleEvents: 96,
    mutableOwnership: 93,
    warnings: [
      "世界不会强迫角色回到原文。",
      "知道原作提供先手，不提供必胜。",
      "世界人物无法感知生成器与现实玩家。",
    ],
  },
  fangYuan: {
    alert: 38,
    cognition: "确认你提前知道酒虫线索",
    currentGoal: "判断酒香来源，并保留替代入口",
    tradeCredit: "谨慎认可",
    verifiedFacts: [
      "你在第 3 日主动查询过野生蛊虫。",
      "你购买了两坛气味异常浓的青竹酒。",
      "你比普通同届更早抵达洞口。",
    ],
    unknown: 3,
  },
};

const HORIZON_RANK = {
  current: 0,
  "one-year": 1,
  "three-years": 2,
};

export function filterSourceOpportunities(
  opportunities,
  { horizon = "current", type = "all", query = "" } = {}
) {
  const selectedRank = HORIZON_RANK[horizon] ?? 0;
  const normalizedQuery = query.trim().toLocaleLowerCase("zh-CN");

  return opportunities.filter((opportunity) => {
    const horizonMatches =
      HORIZON_RANK[opportunity.horizon] <= selectedRank;
    const typeMatches = type === "all" || opportunity.type === type;
    const searchableText = [
      opportunity.title,
      opportunity.subject,
      opportunity.location,
      opportunity.faction,
      opportunity.owner,
      opportunity.summary,
      ...opportunity.tags,
    ]
      .join(" ")
      .toLocaleLowerCase("zh-CN");

    return (
      horizonMatches &&
      typeMatches &&
      (!normalizedQuery || searchableText.includes(normalizedQuery))
    );
  });
}
