export const UI_GROUPS = [
  { id: "entry", label: "进入世界" },
  { id: "character", label: "角色与资源" },
  { id: "intel", label: "世界与情报" },
  { id: "action", label: "行动与战斗" },
  { id: "settlement", label: "结算与离山" },
];

export const RUNTIME_PANEL_TO_PROTOTYPE = Object.freeze({
  panel_character: "UI02",
  panel_aperture: "UI04",
  panel_inventory: "UI05",
  panel_quest: "UI07",
  panel_talent_roster: "UI10",
  panel_canon_lookup: "UI08",
});

export const UI_PANELS = [
  {
    id: "UI00",
    title: "世界生成",
    shortTitle: "生成",
    group: "entry",
    icon: "scan-search",
    scene: "world-map",
  },
  {
    id: "UI01",
    title: "角色 Roll",
    shortTitle: "Roll",
    group: "entry",
    icon: "dices",
    scene: "dorm",
  },
  {
    id: "UI02",
    title: "玩家状态",
    shortTitle: "状态",
    group: "character",
    icon: "user-round",
    scene: "dorm",
  },
  {
    id: "UI03",
    title: "实战成长",
    shortTitle: "成长",
    group: "character",
    icon: "circle-gauge",
    scene: "academy",
  },
  {
    id: "UI04",
    title: "蛊虫喂养",
    shortTitle: "蛊虫",
    group: "character",
    icon: "bug",
    scene: "forest-battle",
  },
  {
    id: "UI05",
    title: "行囊装备",
    shortTitle: "行囊",
    group: "character",
    icon: "backpack",
    scene: "dorm",
  },
  {
    id: "UI06",
    title: "野外旅行",
    shortTitle: "旅行",
    group: "intel",
    icon: "map",
    scene: "world-map",
  },
  {
    id: "UI07",
    title: "任务日志",
    shortTitle: "任务",
    group: "intel",
    icon: "list-tree",
    scene: "village",
  },
  {
    id: "UI08",
    title: "原文查询",
    shortTitle: "原文",
    group: "intel",
    icon: "book-open-text",
    scene: "world-map",
    featured: true,
  },
  {
    id: "UI09",
    title: "人物关系",
    shortTitle: "关系",
    group: "intel",
    icon: "network",
    scene: "village",
  },
  {
    id: "UI10",
    title: "天骄竞争",
    shortTitle: "天骄",
    group: "intel",
    icon: "eye",
    scene: "academy",
  },
  {
    id: "UI11",
    title: "剧情对话",
    shortTitle: "对话",
    group: "action",
    icon: "messages-square",
    scene: "tavern",
  },
  {
    id: "UI12",
    title: "山寨行走",
    shortTitle: "山寨",
    group: "action",
    icon: "footprints",
    scene: "village",
  },
  {
    id: "UI13",
    title: "棋盘战斗",
    shortTitle: "战斗",
    group: "action",
    icon: "swords",
    scene: "forest-battle",
  },
  {
    id: "UI15",
    title: "休息存档",
    shortTitle: "休息",
    group: "settlement",
    icon: "moon-star",
    scene: "dorm",
  },
  {
    id: "UI17",
    title: "离山路线",
    shortTitle: "离山",
    group: "settlement",
    icon: "mountain-snow",
    scene: "world-map",
  },
];

export function getPanel(panelId) {
  return UI_PANELS.find(({ id }) => id === panelId) ?? UI_PANELS[0];
}
