export const UI_GROUPS = [
  { id: "entry", label: "进入世界" },
  { id: "character", label: "角色与资源" },
  { id: "intel", label: "世界与情报" },
  { id: "action", label: "行动与战斗" },
  { id: "settlement", label: "结算与离山" },
];

export const UI_PANELS = [
  {
    id: "UI00",
    title: "世界生成",
    shortTitle: "生成",
    group: "entry",
    icon: "scan-search",
    scene: "world-map",
  },
  {
    id: "UI01",
    title: "角色 Roll",
    shortTitle: "Roll",
    group: "entry",
    icon: "dices",
    scene: "dorm",
  },
  {
    id: "UI02",
    title: "玩家状态",
    shortTitle: "状态",
    group: "character",
    icon: "user-round",
    scene: "dorm",
  },
  {
    id: "UI03",
    title: "空窍修炼",
    shortTitle: "修炼",
    group: "character",
    icon: "circle-gauge",
    scene: "academy",
  },
  {
    id: "UI04",
    title: "蛊虫喂养",
    shortTitle: "蛊虫",
    group: "character",
    icon: "bug",
    scene: "forest-battle",
  },
  {
    id: "UI05",
    title: "行囊所有权",
    shortTitle: "行囊",
    group: "character",
    icon: "backpack",
    scene: "dorm",
  },
  {
    id: "UI06",
    title: "地图旅行",
    shortTitle: "地图",
    group: "intel",
    icon: "map",
    scene: "world-map",
  },
  {
    id: "UI07",
    title: "任务日志",
    shortTitle: "任务",
    group: "intel",
    icon: "list-tree",
    scene: "village",
  },
  {
    id: "UI08",
    title: "原文查询",
    shortTitle: "原文",
    group: "intel",
    icon: "book-open-text",
    scene: "world-map",
    featured: true,
  },
  {
    id: "UI09",
    title: "人物关系",
    shortTitle: "关系",
    group: "intel",
    icon: "network",
    scene: "village",
  },
  {
    id: "UI10",
    title: "方源观察",
    shortTitle: "方源",
    group: "intel",
    icon: "eye",
    scene: "academy",
  },
  {
    id: "UI11",
    title: "对话选择",
    shortTitle: "对话",
    group: "action",
    icon: "messages-square",
    scene: "tavern",
  },
  {
    id: "UI12",
    title: "判定结果",
    shortTitle: "判定",
    group: "action",
    icon: "badge-check",
    scene: "tavern",
  },
  {
    id: "UI13",
    title: "回合战斗",
    shortTitle: "战斗",
    group: "action",
    icon: "swords",
    scene: "forest-battle",
  },
  {
    id: "UI14",
    title: "证据板",
    shortTitle: "证据",
    group: "action",
    icon: "workflow",
    scene: "tavern",
  },
  {
    id: "UI15",
    title: "幕间日终",
    shortTitle: "日终",
    group: "settlement",
    icon: "moon-star",
    scene: "dorm",
  },
  {
    id: "UI16",
    title: "回溯修正",
    shortTitle: "回溯",
    group: "settlement",
    icon: "history",
    scene: "village",
  },
  {
    id: "UI17",
    title: "离山存档",
    shortTitle: "离山",
    group: "settlement",
    icon: "mountain-snow",
    scene: "world-map",
  },
];

export function getPanel(panelId) {
  return UI_PANELS.find(({ id }) => id === panelId) ?? UI_PANELS[0];
}
