export const MAPS = {
  world: {
    name: "青茅山",
    background: "world-map",
    spawns: {
      default: { x: 540, y: 630 },
      fromVillage: { x: 900, y: 185 },
      fromForest: { x: 640, y: 535 },
    },
    interactables: [
      {
        id: "enter-village",
        name: "古月山寨",
        kind: "exit",
        x: 910,
        y: 125,
        radius: 78,
        target: "village",
        entrance: "fromWorld",
        cost: 1,
      },
      {
        id: "enter-forest",
        name: "竹林猎场",
        kind: "event",
        x: 635,
        y: 510,
        radius: 82,
      },
    ],
  },
  village: {
    name: "古月山寨",
    background: "village",
    spawns: {
      default: { x: 640, y: 660 },
      fromWorld: { x: 1160, y: 205 },
      fromTavern: { x: 285, y: 405 },
      fromAcademy: { x: 715, y: 205 },
      fromDorm: { x: 970, y: 540 },
    },
    interactables: [
      {
        id: "leave-village",
        name: "山寨外道",
        kind: "exit",
        x: 1180,
        y: 165,
        radius: 70,
        target: "world",
        entrance: "fromVillage",
        cost: 1,
      },
      {
        id: "enter-tavern",
        name: "醉仙楼",
        kind: "exit",
        x: 285,
        y: 365,
        radius: 64,
        target: "tavern",
        entrance: "default",
      },
      {
        id: "enter-academy",
        name: "古月学堂",
        kind: "exit",
        x: 715,
        y: 165,
        radius: 64,
        target: "academy",
        entrance: "default",
      },
      {
        id: "enter-dorm",
        name: "弟子住处",
        kind: "exit",
        x: 970,
        y: 490,
        radius: 66,
        target: "dorm",
        entrance: "default",
      },
      {
        id: "market-stall",
        name: "市集钱袋",
        kind: "object",
        x: 405,
        y: 520,
        radius: 70,
        color: 0xd6b160,
      },
      {
        id: "fang-yuan",
        name: "方源",
        kind: "npc",
        x: 645,
        y: 430,
        radius: 78,
        color: 0x8799a8,
      },
    ],
  },
  tavern: {
    name: "醉仙楼",
    background: "tavern",
    spawns: {
      default: { x: 640, y: 650 },
    },
    interactables: [
      {
        id: "leave-tavern",
        name: "返回山寨",
        kind: "exit",
        x: 640,
        y: 670,
        radius: 68,
        target: "village",
        entrance: "fromTavern",
      },
      {
        id: "clerk",
        name: "客栈伙计",
        kind: "npc",
        x: 475,
        y: 315,
        radius: 76,
        color: 0x9b6a43,
      },
      {
        id: "patrol-ledger",
        name: "巡夜薄",
        kind: "object",
        x: 650,
        y: 245,
        radius: 72,
        color: 0xb9a16f,
      },
      {
        id: "merchant",
        name: "行脚商贩",
        kind: "npc",
        x: 845,
        y: 390,
        radius: 80,
        color: 0x9d7445,
      },
      {
        id: "wine-jars",
        name: "异香酒坛",
        kind: "object",
        x: 1030,
        y: 245,
        radius: 82,
        color: 0xb95747,
      },
      {
        id: "back-room",
        name: "后房夹层",
        kind: "object",
        x: 1080,
        y: 345,
        radius: 78,
        color: 0x6f9d74,
      },
    ],
  },
  academy: {
    name: "古月学堂",
    background: "academy",
    spawns: {
      default: { x: 640, y: 655 },
    },
    interactables: [
      {
        id: "leave-academy",
        name: "返回山寨",
        kind: "exit",
        x: 640,
        y: 670,
        radius: 68,
        target: "village",
        entrance: "fromAcademy",
      },
      {
        id: "instructor",
        name: "学堂家老",
        kind: "npc",
        x: 640,
        y: 220,
        radius: 88,
        color: 0x6d8d7c,
      },
    ],
  },
  dorm: {
    name: "弟子住处",
    background: "dorm",
    spawns: {
      default: { x: 640, y: 660 },
    },
    interactables: [
      {
        id: "leave-dorm",
        name: "返回山寨",
        kind: "exit",
        x: 640,
        y: 675,
        radius: 68,
        target: "village",
        entrance: "fromDorm",
      },
      {
        id: "bed",
        name: "木床",
        kind: "object",
        x: 350,
        y: 230,
        radius: 86,
        color: 0x7b8fa3,
      },
      {
        id: "floor-hatch",
        name: "暗格",
        kind: "object",
        x: 950,
        y: 430,
        radius: 82,
        color: 0xb19a69,
      },
      {
        id: "meditation-mat",
        name: "蒲团",
        kind: "object",
        x: 540,
        y: 455,
        radius: 82,
        color: 0x738a62,
      },
    ],
  },
};

export const ASSETS = [
  ["world-map", "/assets/game/environments/world-map.png"],
  ["village", "/assets/game/environments/village.png"],
  ["tavern", "/assets/game/environments/tavern.png"],
  ["academy", "/assets/game/environments/academy.png"],
  ["dorm", "/assets/game/environments/dorm.png"],
  ["forest-battle", "/assets/game/environments/forest-battle.png"],
];
